"""A deterministic synthetic price source.

This is what makes CI hermetic, ``make demo`` work with the network off, and the
whole ingestion path testable without a vendor. It is also the third
implementation that keeps the ``SourceClient`` port honest: a port with two
implementations is a guess, and one of these two is a fake.

The series is not a random walk. Returns are generated by a GARCH(1,1)-style
process so volatility clusters the way real returns do — quiet stretches broken
by bursts. That matters because a strategy tested against constant-volatility
noise will size positions in a way that falls apart on real data, and because
the volatility model of a later milestone needs something with structure to
find.
"""

from __future__ import annotations

import hashlib
import math
import random
from datetime import date, timedelta

import polars as pl

from finflow.contracts.frames import OhlcvBar, validate_frame
from finflow.contracts.sources import SourceKey
from finflow.ports.source import SourceCapabilities

SOURCE = SourceKey.SYNTHETIC

# GARCH(1,1) at roughly equity-index parameters: persistent, mean-reverting.
_OMEGA = 0.000002
_ALPHA = 0.08
_BETA = 0.90
_ANNUAL_DRIFT = 0.06
_TRADING_DAYS = 252


class SyntheticClient:
    """Generates reproducible OHLCV for any symbol."""

    def __init__(self, *, seed: int = 0) -> None:
        self._seed = seed

    def capabilities(self) -> SourceCapabilities:
        """Always available, never rate-limited, no credential."""
        return SourceCapabilities(
            key=SOURCE,
            supports_ohlcv=True,
            supports_macro=False,
            requires_auth=False,
        )

    def _rng(self, symbol: str) -> random.Random:
        """Seed from the symbol so each instrument gets its own stable series.

        Hashed rather than using ``hash()``, which is salted per process and
        would make the "deterministic" in this class's name false.
        """
        digest = hashlib.sha256(f"{self._seed}:{symbol}".encode()).hexdigest()
        return random.Random(int(digest[:16], 16))

    def fetch(self, symbol: str, start: date, end: date) -> pl.DataFrame:
        """Return bars for every weekday in the range.

        Weekends are skipped but holidays are not: this is a price generator,
        not a calendar. Calendar alignment is the warehouse's job, and a
        synthetic source that quietly implemented it would hide gaps the real
        checks are supposed to catch.
        """
        if start > end:
            return pl.DataFrame(schema={f: OhlcvBar.dtypes[f] for f in OhlcvBar.columns})

        rng = self._rng(symbol)
        price = 50.0 + rng.random() * 150.0
        variance = _OMEGA / (1 - _ALPHA - _BETA)
        drift = _ANNUAL_DRIFT / _TRADING_DAYS

        rows = []
        day = start
        while day <= end:
            if day.weekday() < 5:
                shock = rng.gauss(0.0, 1.0)
                ret = drift + math.sqrt(variance) * shock
                variance = _OMEGA + _ALPHA * (ret - drift) ** 2 + _BETA * variance

                open_ = price
                close = max(0.01, price * math.exp(ret))
                # Intraday range scaled to the day's own volatility, so a
                # volatile day is a wide day.
                spread = abs(close - open_) + price * math.sqrt(variance) * rng.uniform(0.2, 1.2)
                high = max(open_, close) + spread * rng.random()
                low = max(0.01, min(open_, close) - spread * rng.random())

                rows.append(
                    {
                        "symbol": symbol,
                        "date": day,
                        "open": round(open_, 4),
                        "high": round(high, 4),
                        "low": round(low, 4),
                        "close": round(close, 4),
                        "volume": float(int(rng.lognormvariate(13.5, 0.6))),
                    }
                )
                price = close
            day += timedelta(days=1)

        if not rows:
            return pl.DataFrame(schema={f: OhlcvBar.dtypes[f] for f in OhlcvBar.columns})

        frame = pl.DataFrame(rows).select(OhlcvBar.columns)
        validate_frame(OhlcvBar, frame)
        return frame
