select
    symbol as instrument_key,
    symbol,
    name,
    asset_class,
    sub_class,
    exchange,
    currency,
    calendar,
    inception,
    backfill_start,
    delisted,
    return_basis,
    commission_bps,
    spread_bps,
    min_adv_usd,
    ucits_equivalent,
    tradeable_eu,
    enabled,
    registry_commit,
    valid_from,
    cast(null as timestamp) as valid_to,
    true as is_current
from {{ source('bronze', 'registry_instruments') }}
